/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelgrupo10.vistas;

/**
 *
 * @author nahue
 */
public class MenuListaCategorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuListaCategorias
     */
    public MenuListaCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JRBnro1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        JRBnro2 = new javax.swing.JRadioButton();
        JRBnro3 = new javax.swing.JRadioButton();
        JRBnro4 = new javax.swing.JRadioButton();
        JRBnro5 = new javax.swing.JRadioButton();
        JRBnro6 = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Lista de categorias");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JRBnro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBnro1.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Para listar por numero de personas seleccionar alguna de las opciones");

        JRBnro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBnro2.setText("2");

        JRBnro3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBnro3.setText("3");

        JRBnro4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBnro4.setText("4");

        JRBnro5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBnro5.setText("5");

        JRBnro6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBnro6.setText("6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(JRBnro1)
                        .addGap(34, 34, 34)
                        .addComponent(JRBnro2)
                        .addGap(36, 36, 36)
                        .addComponent(JRBnro3)
                        .addGap(36, 36, 36)
                        .addComponent(JRBnro4)
                        .addGap(36, 36, 36)
                        .addComponent(JRBnro5)
                        .addGap(34, 34, 34)
                        .addComponent(JRBnro6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBnro1)
                    .addComponent(JRBnro2)
                    .addComponent(JRBnro3)
                    .addComponent(JRBnro4)
                    .addComponent(JRBnro5)
                    .addComponent(JRBnro6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRBnro1;
    private javax.swing.JRadioButton JRBnro2;
    private javax.swing.JRadioButton JRBnro3;
    private javax.swing.JRadioButton JRBnro4;
    private javax.swing.JRadioButton JRBnro5;
    private javax.swing.JRadioButton JRBnro6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
