/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelgrupo10.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author nahue
 */
public class MenuIniciarSesion extends javax.swing.JInternalFrame {
 private MenuPrincipal menuPrincipal;
    /**
     * Creates new form MenuIniciarSesion
     */
    public MenuIniciarSesion(MenuPrincipal menuPrincipal) {
        initComponents();
        this.menuPrincipal=menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscIniciosesion = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JPFcontraseña = new javax.swing.JPasswordField();
        JBingresar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        EscIniciosesion.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Iniciar sesion");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Ingrese su usuario");

        JTusuario.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("Ingrese su contraseña");

        JPFcontraseña.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        JBingresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JBingresar.setText("Ingresar");
        JBingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBingresarActionPerformed(evt);
            }
        });

        EscIniciosesion.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscIniciosesion.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscIniciosesion.setLayer(JTusuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscIniciosesion.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscIniciosesion.setLayer(JPFcontraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EscIniciosesion.setLayer(JBingresar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscIniciosesionLayout = new javax.swing.GroupLayout(EscIniciosesion);
        EscIniciosesion.setLayout(EscIniciosesionLayout);
        EscIniciosesionLayout.setHorizontalGroup(
            EscIniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscIniciosesionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(EscIniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscIniciosesionLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(EscIniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPFcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(209, 209, 209))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscIniciosesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(232, 232, 232))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscIniciosesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EscIniciosesionLayout.setVerticalGroup(
            EscIniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscIniciosesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(EscIniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(JTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(EscIniciosesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JPFcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(JBingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EscIniciosesion)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscIniciosesion)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBingresarActionPerformed
        // TODO add your handling code here:
        if(JTusuario.getText().equalsIgnoreCase("apple20") && JPFcontraseña.getText().equalsIgnoreCase("grupo10")){
        
        MenuAdministracion menua= new MenuAdministracion(menuPrincipal);
        menua.setVisible(true);
        menuPrincipal.getEscritorio().add(menua);
        menuPrincipal.getEscritorio().moveToFront(menua);
        
        
        }else if(JTusuario.getText().isEmpty() || JPFcontraseña.getText().isEmpty()){
        
        
        JOptionPane.showMessageDialog(null, "No Dejar Usuario o Contraseña Sin Completar");
        
        
        }else{
        
        JOptionPane.showMessageDialog(null, "Usuario Y/O Contraseñas Incorrectos");
        
        }
   
        
    }//GEN-LAST:event_JBingresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscIniciosesion;
    private javax.swing.JButton JBingresar;
    private javax.swing.JPasswordField JPFcontraseña;
    private javax.swing.JTextField JTusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
